/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.topggdsl.parser.antlr.internal.InternalTopggDSLParser;
import uk.ac.kcl.topggdsl.services.TopggDSLGrammarAccess;

public class TopggDSLParser extends AbstractAntlrParser {

	@Inject
	private TopggDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTopggDSLParser createParser(XtextTokenStream stream) {
		return new InternalTopggDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TopggDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TopggDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
