/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TopggDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/kcl/topggdsl/parser/antlr/internal/InternalTopggDSL.tokens");
	}
}
