/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.topggDSL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.topggdsl.topggDSL.Bot;
import uk.ac.kcl.topggdsl.topggDSL.Review;
import uk.ac.kcl.topggdsl.topggDSL.Status;
import uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Review</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl#getId <em>Id</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl#getBotRef <em>Bot Ref</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl#getStatus <em>Status</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl#getReason <em>Reason</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl#getReviewer <em>Reviewer</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReviewImpl extends EntryImpl implements Review
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getBotRef() <em>Bot Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBotRef()
   * @generated
   * @ordered
   */
  protected Bot botRef;

  /**
   * The default value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected static final Status STATUS_EDEFAULT = Status.APPROVED;

  /**
   * The cached value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected Status status = STATUS_EDEFAULT;

  /**
   * The default value of the '{@link #getReason() <em>Reason</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReason()
   * @generated
   * @ordered
   */
  protected static final String REASON_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReason() <em>Reason</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReason()
   * @generated
   * @ordered
   */
  protected String reason = REASON_EDEFAULT;

  /**
   * The default value of the '{@link #getReviewer() <em>Reviewer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReviewer()
   * @generated
   * @ordered
   */
  protected static final String REVIEWER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReviewer() <em>Reviewer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReviewer()
   * @generated
   * @ordered
   */
  protected String reviewer = REVIEWER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReviewImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TopggDSLPackage.Literals.REVIEW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TopggDSLPackage.REVIEW__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bot getBotRef()
  {
    if (botRef != null && botRef.eIsProxy())
    {
      InternalEObject oldBotRef = (InternalEObject)botRef;
      botRef = (Bot)eResolveProxy(oldBotRef);
      if (botRef != oldBotRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TopggDSLPackage.REVIEW__BOT_REF, oldBotRef, botRef));
      }
    }
    return botRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Bot basicGetBotRef()
  {
    return botRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBotRef(Bot newBotRef)
  {
    Bot oldBotRef = botRef;
    botRef = newBotRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TopggDSLPackage.REVIEW__BOT_REF, oldBotRef, botRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Status getStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStatus(Status newStatus)
  {
    Status oldStatus = status;
    status = newStatus == null ? STATUS_EDEFAULT : newStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TopggDSLPackage.REVIEW__STATUS, oldStatus, status));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getReason()
  {
    return reason;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReason(String newReason)
  {
    String oldReason = reason;
    reason = newReason;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TopggDSLPackage.REVIEW__REASON, oldReason, reason));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getReviewer()
  {
    return reviewer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReviewer(String newReviewer)
  {
    String oldReviewer = reviewer;
    reviewer = newReviewer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TopggDSLPackage.REVIEW__REVIEWER, oldReviewer, reviewer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TopggDSLPackage.REVIEW__ID:
        return getId();
      case TopggDSLPackage.REVIEW__BOT_REF:
        if (resolve) return getBotRef();
        return basicGetBotRef();
      case TopggDSLPackage.REVIEW__STATUS:
        return getStatus();
      case TopggDSLPackage.REVIEW__REASON:
        return getReason();
      case TopggDSLPackage.REVIEW__REVIEWER:
        return getReviewer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TopggDSLPackage.REVIEW__ID:
        setId((String)newValue);
        return;
      case TopggDSLPackage.REVIEW__BOT_REF:
        setBotRef((Bot)newValue);
        return;
      case TopggDSLPackage.REVIEW__STATUS:
        setStatus((Status)newValue);
        return;
      case TopggDSLPackage.REVIEW__REASON:
        setReason((String)newValue);
        return;
      case TopggDSLPackage.REVIEW__REVIEWER:
        setReviewer((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TopggDSLPackage.REVIEW__ID:
        setId(ID_EDEFAULT);
        return;
      case TopggDSLPackage.REVIEW__BOT_REF:
        setBotRef((Bot)null);
        return;
      case TopggDSLPackage.REVIEW__STATUS:
        setStatus(STATUS_EDEFAULT);
        return;
      case TopggDSLPackage.REVIEW__REASON:
        setReason(REASON_EDEFAULT);
        return;
      case TopggDSLPackage.REVIEW__REVIEWER:
        setReviewer(REVIEWER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TopggDSLPackage.REVIEW__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case TopggDSLPackage.REVIEW__BOT_REF:
        return botRef != null;
      case TopggDSLPackage.REVIEW__STATUS:
        return status != STATUS_EDEFAULT;
      case TopggDSLPackage.REVIEW__REASON:
        return REASON_EDEFAULT == null ? reason != null : !REASON_EDEFAULT.equals(reason);
      case TopggDSLPackage.REVIEW__REVIEWER:
        return REVIEWER_EDEFAULT == null ? reviewer != null : !REVIEWER_EDEFAULT.equals(reviewer);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(", status: ");
    result.append(status);
    result.append(", reason: ");
    result.append(reason);
    result.append(", reviewer: ");
    result.append(reviewer);
    result.append(')');
    return result.toString();
  }

} //ReviewImpl
