/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.validation

import org.eclipse.xtext.validation.Check
import uk.ac.kcl.topggdsl.topggDSL.Review
import uk.ac.kcl.topggdsl.topggDSL.Bot
import uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage

class TopggDSLValidator extends AbstractTopggDSLValidator {

    @Check
    def void checkReviewHasValidBot(Review review) {
        if (review.botRef === null) {
            error("Review must refer to a valid bot.",
                TopggDSLPackage.Literals.REVIEW__BOT_REF)
        }
    }

    @Check
    def void checkReasonNotEmpty(Review review) {
        if (review.reason.nullOrEmpty) {
            warning("Review should have a reason.",
                TopggDSLPackage.Literals.REVIEW__REASON)
        }
    }

    @Check
    def void checkBotHasAtLeastOneTag(Bot bot) {
        if (bot.tags.empty) {
            warning("Bot should have at least one tag.",
                TopggDSLPackage.Literals.BOT__TAGS)
        }
    }
}
