/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTopggDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage.eINSTANCE);
		return result;
	}
}
