/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TopggDSLRuntimeModule extends AbstractTopggDSLRuntimeModule {
}
