/*
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TopggDSLStandaloneSetup extends TopggDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new TopggDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
