/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.topggDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getEntry()
 * @model
 * @generated
 */
public interface Entry extends EObject
{
} // Entry
