/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.topggDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.Model#getEntries <em>Entries</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entries</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.topggdsl.topggDSL.Entry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' containment reference list.
   * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getModel_Entries()
   * @model containment="true"
   * @generated
   */
  EList<Entry> getEntries();

} // Model
