/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.topggDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Review</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.Review#getId <em>Id</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.Review#getBotRef <em>Bot Ref</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.Review#getStatus <em>Status</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.Review#getReason <em>Reason</em>}</li>
 *   <li>{@link uk.ac.kcl.topggdsl.topggDSL.Review#getReviewer <em>Reviewer</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getReview()
 * @model
 * @generated
 */
public interface Review extends Entry
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getReview_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Bot Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bot Ref</em>' reference.
   * @see #setBotRef(Bot)
   * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getReview_BotRef()
   * @model
   * @generated
   */
  Bot getBotRef();

  /**
   * Sets the value of the '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getBotRef <em>Bot Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bot Ref</em>' reference.
   * @see #getBotRef()
   * @generated
   */
  void setBotRef(Bot value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.topggdsl.topggDSL.Status}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see uk.ac.kcl.topggdsl.topggDSL.Status
   * @see #setStatus(Status)
   * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getReview_Status()
   * @model
   * @generated
   */
  Status getStatus();

  /**
   * Sets the value of the '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see uk.ac.kcl.topggdsl.topggDSL.Status
   * @see #getStatus()
   * @generated
   */
  void setStatus(Status value);

  /**
   * Returns the value of the '<em><b>Reason</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reason</em>' attribute.
   * @see #setReason(String)
   * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getReview_Reason()
   * @model
   * @generated
   */
  String getReason();

  /**
   * Sets the value of the '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getReason <em>Reason</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reason</em>' attribute.
   * @see #getReason()
   * @generated
   */
  void setReason(String value);

  /**
   * Returns the value of the '<em><b>Reviewer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reviewer</em>' attribute.
   * @see #setReviewer(String)
   * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLPackage#getReview_Reviewer()
   * @model
   * @generated
   */
  String getReviewer();

  /**
   * Sets the value of the '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getReviewer <em>Reviewer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reviewer</em>' attribute.
   * @see #getReviewer()
   * @generated
   */
  void setReviewer(String value);

} // Review
