/**
 * generated by Xtext 2.38.0
 */
package uk.ac.kcl.topggdsl.topggDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.topggdsl.topggDSL.TopggDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TopggDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "topggDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kcl.ac.uk/topggdsl/TopggDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "topggDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TopggDSLPackage eINSTANCE = uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.ModelImpl
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTRIES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.EntryImpl <em>Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.EntryImpl
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getEntry()
   * @generated
   */
  int ENTRY = 1;

  /**
   * The number of structural features of the '<em>Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.BotImpl <em>Bot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.BotImpl
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getBot()
   * @generated
   */
  int BOT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT__NAME = ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT__PREFIX = ENTRY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Tags</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT__TAGS = ENTRY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT__DESCRIPTION = ENTRY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Bot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOT_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl <em>Review</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getReview()
   * @generated
   */
  int REVIEW = 3;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__ID = ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Bot Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__BOT_REF = ENTRY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__STATUS = ENTRY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Reason</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__REASON = ENTRY_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Reviewer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW__REVIEWER = ENTRY_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Review</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVIEW_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link uk.ac.kcl.topggdsl.topggDSL.Status <em>Status</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.topggdsl.topggDSL.Status
   * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getStatus()
   * @generated
   */
  int STATUS = 4;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.topggdsl.topggDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.topggdsl.topggDSL.Model#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Model#getEntries()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Entries();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.topggdsl.topggDSL.Entry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Entry
   * @generated
   */
  EClass getEntry();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.topggdsl.topggDSL.Bot <em>Bot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bot</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Bot
   * @generated
   */
  EClass getBot();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.topggdsl.topggDSL.Bot#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Bot#getName()
   * @see #getBot()
   * @generated
   */
  EAttribute getBot_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.topggdsl.topggDSL.Bot#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Bot#getPrefix()
   * @see #getBot()
   * @generated
   */
  EAttribute getBot_Prefix();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.topggdsl.topggDSL.Bot#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Tags</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Bot#getTags()
   * @see #getBot()
   * @generated
   */
  EAttribute getBot_Tags();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.topggdsl.topggDSL.Bot#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Bot#getDescription()
   * @see #getBot()
   * @generated
   */
  EAttribute getBot_Description();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.topggdsl.topggDSL.Review <em>Review</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Review</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Review
   * @generated
   */
  EClass getReview();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Review#getId()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_Id();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getBotRef <em>Bot Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Bot Ref</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Review#getBotRef()
   * @see #getReview()
   * @generated
   */
  EReference getReview_BotRef();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Review#getStatus()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_Status();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getReason <em>Reason</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reason</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Review#getReason()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_Reason();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.topggdsl.topggDSL.Review#getReviewer <em>Reviewer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reviewer</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Review#getReviewer()
   * @see #getReview()
   * @generated
   */
  EAttribute getReview_Reviewer();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.topggdsl.topggDSL.Status <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Status</em>'.
   * @see uk.ac.kcl.topggdsl.topggDSL.Status
   * @generated
   */
  EEnum getStatus();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TopggDSLFactory getTopggDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.ModelImpl
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTRIES = eINSTANCE.getModel_Entries();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.EntryImpl <em>Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.EntryImpl
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getEntry()
     * @generated
     */
    EClass ENTRY = eINSTANCE.getEntry();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.BotImpl <em>Bot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.BotImpl
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getBot()
     * @generated
     */
    EClass BOT = eINSTANCE.getBot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOT__NAME = eINSTANCE.getBot_Name();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOT__PREFIX = eINSTANCE.getBot_Prefix();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOT__TAGS = eINSTANCE.getBot_Tags();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOT__DESCRIPTION = eINSTANCE.getBot_Description();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl <em>Review</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.ReviewImpl
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getReview()
     * @generated
     */
    EClass REVIEW = eINSTANCE.getReview();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__ID = eINSTANCE.getReview_Id();

    /**
     * The meta object literal for the '<em><b>Bot Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REVIEW__BOT_REF = eINSTANCE.getReview_BotRef();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__STATUS = eINSTANCE.getReview_Status();

    /**
     * The meta object literal for the '<em><b>Reason</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__REASON = eINSTANCE.getReview_Reason();

    /**
     * The meta object literal for the '<em><b>Reviewer</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVIEW__REVIEWER = eINSTANCE.getReview_Reviewer();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.topggdsl.topggDSL.Status <em>Status</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.topggdsl.topggDSL.Status
     * @see uk.ac.kcl.topggdsl.topggDSL.impl.TopggDSLPackageImpl#getStatus()
     * @generated
     */
    EEnum STATUS = eINSTANCE.getStatus();

  }

} //TopggDSLPackage
